### ISSUE TITLE
Closing Port Doesn't Always Work

### ISSUE THREAD

**Issue by jredfox** [adolfintel/WaifUPnP#2]
router xfiniti:
program tested with: minecraft with lan-essentials(Not quite up to date):
https://github.com/jredfox/lanessentials
![waifupnp](https://user-images.githubusercontent.com/9736369/41815111-53541dcc-7726-11e8-9ecf-df90616fe9bb.PNG)

Code Ran during test run:
https://gist.github.com/jredfox/b98f0dca5da13d4d359b9fa6fcadfdb1

Test run:
while game is still running close port > doesn't always close port
while game has closed close port > doesn't always remove entry from http://10.1.10.1 internet service provider
when game is closed try and close the port. 

Test run 2:
when application has been closed for several minuets close the port works

Test run 3:
**when minecraft is still port forwarding close UDP port instead of TCP port and my port did get closed**. Maybe your close UDP port and close TCP port are named wrong? I have an unmodified latest version of your library

Test run was tested with this code to close the port tried with both and just plain tcp which is what minecraft uses to host lan.

I hope you can make it remove the entry better since I have tried both while the program was running when it was closing and after it closed same result. Maybe it's an issue/bug with my internet service provider.

**Comment by adolfintel** [comment]
You've already fixed this, so I'm closing the issue.
