### ISSUE TITLE
License/Permission Issue

### ISSUE THREAD

**Issue by jredfox** [adolfintel/WaifUPnP#9]
Hey minecraft doesn't have your library installed. Can I distribute this jar for a networking mod? I don't see a release forums like maven and it might fail anyways.

I don't understand the license under gnu it says may convey a modified copy what the heck does that even mean can I or can I not redistribute it?

I would of course give a credits to you and a link back.

**Comment by adolfintel** [comment]
Hi,
The LGPL allows you to redistribute this library, even if it's bundled with some proprietary program. The only restriction is that if you make changes to the library itself, the modified version must remain open source and under the same LGPL license (in other words, send the changes to me).
For any additional info, feel free to contact me.

**Comment by jredfox** [comment]
I believe I may or may not have fixed something but, yes it's open source. I can add the license files.

**Comment by adolfintel** [comment]
Is it the fork you have on your profile?

**Comment by jredfox** [comment]
https://github.com/jredfox/WaifUPnP

**Comment by jredfox** [comment]
I recommend using something more open so people can easily use it for a library like https://creativecommons.org/licenses/by-nc/4.0/

**Comment by adolfintel** [comment]
It's ok, it's a perfectly legitimate use for LGPL.

**Comment by jredfox** [comment]
I understand if it were a game but, will respect your wishes here and keep the promise

**Comment by adolfintel** [comment]
I use LGPL on purpose. A lot of libraries nowadays use the more permissive BSD license, but I don't like that because it allows people to take my code, make changes and not give them to me, which is unacceptable in my opinion.

**Comment by jredfox** [comment]
So you want me when I am done patching it to give you back the code don't worry I will.

There was something I wrote down last time I reported an issue It's still not fixed got to figure it out first don't remember what it was
